export const crosswordData = [
  { word: "MEXICO", clue: "País de habla hispana conocido por su tequila y mariachis" },
  { word: "TACO", clue: "Platillo típico en tortilla de maíz con carne y salsa" },
  { word: "MARIACHI", clue: "Música folclórica mexicana tradicional con trompetas y guitarras" },
  { word: "TEQUILA", clue: "Bebida alcohólica destilada originaria de Jalisco" },
  { word: "FRIDA", clue: "Pintora famosa surrealista de la Casa Azul, apellido Kahlo" },
  { word: "KAHLO", clue: "Apellido de la pintora mexicana Frida" },
  { word: "MAIZ", clue: "Cereal base de la alimentación mexicana tradicional" },
  { word: "SALSA", clue: "Acompañamiento picante para la comida" },
  { word: "CHILE", clue: "Ingrediente que le da el picante a la comida mexicana" },
  { word: "POZOLE", clue: "Caldo tradicional con granos de maíz y carne" },
  { word: "MEZCAL", clue: "Bebida artesanal hecha de agave, similar al tequila" },
  { word: "LOTERIA", clue: "Juego de cartas tradicional mexicano con frijoles" },
  { word: "AGAVE", clue: "Planta de la que se extrae el tequila y el mezcal" },
  { word: "CANCUN", clue: "Famoso destino turístico de playas en Quintana Roo" },
  { word: "ZOCALO", clue: "Plaza principal de la Ciudad de México" },
  { word: "MAYAS", clue: "Antigua civilización que construyó Chichén Itzá" },
  { word: "AZTECAS", clue: "Civilización fundadora de Tenochtitlan en el Valle de México" },
  { word: "PIÑATA", clue: "Objeto de barro o cartón decorado que se rompe en fiestas" },
  { word: "TAMAL", clue: "Masa de maíz rellena envuelta en hojas de mazorca o plátano" },
  { word: "MOLE", clue: "Salsa densa tradicional hecha con chiles y chocolate" },
  { word: "CACAO", clue: "Semilla base del chocolate usada como moneda por los aztecas" },
  { word: "SIERRA", clue: "Cadena montañosa como la Sierra Madre" },
  { word: "REVOLUCION", clue: "Conflicto histórico iniciado en 1910 por Francisco I. Madero" },
  { word: "JUAREZ", clue: "Benito, presidente conocido como el Benemérito de las Américas" },
  { word: "HIDALGO", clue: "Miguel, cura iniciador de la Independencia de México" },
  { word: "CATRINA", clue: "Calavera creada por José Guadalupe Posada para el Día de Muertos" },
  { word: "OFRENDA", clue: "Altar colocado para recordar a los difuntos en su día" },
  { word: "GUADALUPE", clue: "Basílica o virgen patrona muy venerada en el país" },
  { word: "CHINAMPA", clue: "Método de cultivo prehispánico flotante en Xochimilco" },
  { word: "MEXICA", clue: "Nombre original del pueblo azteca antes de la conquista" },
  { word: "XOLO", clue: "Perro sagrado prehispánico sin pelo que guía a las almas" },
  { word: "ALBURES", clue: "Juegos de palabras de doble sentido de la picardía mexicana" },
  { word: "HUAPANGO", clue: "Baile y género musical zapateado típico de la Huasteca" },
  { word: "ENCHILADA", clue: "Tortilla rellena bañada en salsa picante" },
  { word: "CHIAPAS", clue: "Estado conocido por la selva Lacandona y el Cañón del Sumidero" },
  { word: "OAXACA", clue: "Estado cuna del mezcal y las tlayudas" },
  { word: "JALISCO", clue: "Estado de donde es originario el tequila y el mariachi" },
  { word: "YUCATAN", clue: "Península donde cayó el meteorito de los dinosaurios" },
  { word: "MARIPOSA", clue: "Insecto monarca que migra desde Canadá hasta Michoacán" },
  { word: "GRIJALVA", clue: "Río caudaloso del sur que cruza el Cañón del Sumidero" },
  { word: "NAHUATL", clue: "Lengua indígena más hablada de México" },
  { word: "CENOTE", clue: "Pozo de agua dulce sagrado para los mayas" },
  { word: "ALEBRIJE", clue: "Artesanía de cartón de colores con formas de animales fantásticos" },
  { word: "CHAPULIN", clue: "Insecto comestible tradicional sazonado con limón y sal" },
  { word: "MICHOACAN", clue: "Estado famoso por Janitzio y el santuario de la mariposa monarca" },
  { word: "VERACRUZ", clue: "Puerto fundado por Hernán Cortés con música de jarana" },
  { word: "TLAYUDA", clue: "Tortilla gigante de maíz con asiento, frijoles, tasajo y quesillo" },
  { word: "QUESILLO", clue: "Queso hebra o de Oaxaca típico para quesadillas" },
  { word: "CHURRO", clue: "Postre frito alargado espolvoreado con azúcar y canela" },
  { word: "HORCHATA", clue: "Agua fresca tradicional hecha a base de arroz y canela" }
];
